use std::{
    fs,
    path::{Path, PathBuf},
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use archunit::{
    ArchUnitError, MetricsExportOptions, MetricsExporter, MetricsReportData, metrics_in,
};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

struct TemporaryDirectory(PathBuf);

impl TemporaryDirectory {
    fn new(label: &str) -> Self {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system clock should follow the Unix epoch")
            .as_nanos();
        Self(std::env::temp_dir().join(format!(
            "archunit-public-metrics-{label}-{}-{nonce}",
            process::id()
        )))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TemporaryDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn stable_options() -> MetricsExportOptions {
    MetricsExportOptions::new()
        .with_title("Stable Metrics")
        .with_timestamp(false)
}

#[test]
fn public_exporter_renders_escaped_offline_data_and_optional_timestamp() {
    let data = MetricsReportData::from([
        ("<script>metric</script>".to_owned(), "2 & 3".to_owned()),
        ("cohesion".to_owned(), "0.25".to_owned()),
    ]);
    let safe = MetricsExporter::render_html_with(
        &data,
        &stable_options().with_custom_css("body { color: navy; } </style><script>bad()</script>"),
    )
    .expect("valid report data should render");
    let timestamped = MetricsExporter::render_html(&MetricsReportData::new())
        .expect("default report should render");

    assert!(safe.contains("<title>Stable Metrics</title>"));
    assert!(safe.contains("&lt;script&gt;metric&lt;/script&gt;"));
    assert!(safe.contains("2 &amp; 3"));
    assert!(safe.contains("<\\/style>"));
    assert!(!safe.contains("</style><script>"));
    assert!(!safe.contains("Generated:"));
    assert!(timestamped.contains("<p class=\"timestamp\">Generated: "));
    assert!(timestamped.contains("Z</p>"));
    assert!(timestamped.contains("No metric data."));
}

#[test]
fn count_lcom_and_distance_builders_export_complete_scoped_families() {
    let output = TemporaryDirectory::new("families");
    let metrics_root = fixture("metrics_project");
    let distance_root = fixture("distance_project");

    let count_path = metrics_in(metrics_root.as_path())
        .with_name("domain.rs")
        .count()
        .export_as_html_with(output.path().join("reports/count"), &stable_options())
        .expect("count report should export");
    let lcom_path = metrics_in(metrics_root)
        .for_types_matching("Service")
        .lcom()
        .export_as_html_with(output.path().join("reports/lcom"), &stable_options())
        .expect("LCOM report should export");
    let distance_path = metrics_in(distance_root)
        .with_name("lib.rs")
        .distance()
        .export_as_html_with(output.path().join("reports/distance"), &stable_options())
        .expect("distance report should export");

    let count = fs::read_to_string(&count_path).expect("count report should be UTF-8");
    let lcom = fs::read_to_string(&lcom_path).expect("LCOM report should be UTF-8");
    let distance = fs::read_to_string(&distance_path).expect("distance report should be UTF-8");

    assert_eq!(count_path, output.path().join("reports/count.html"));
    assert_eq!(lcom_path, output.path().join("reports/lcom.html"));
    assert_eq!(distance_path, output.path().join("reports/distance.html"));
    assert!(count.contains("method_count [src/domain.rs:Service]"));
    assert!(count.contains("lines_of_code [src/domain.rs]"));
    assert!(count.contains("associated_functions [src/domain.rs]"));
    assert!(lcom.contains("lcom4 [src/domain.rs:Service]"));
    assert!(lcom.contains("lcom_star [src/domain.rs:Service]"));
    assert!(distance.contains("instability [src/lib.rs]"));
    assert!(distance.contains("distance_from_main_sequence [src/lib.rs]"));
    assert!(distance.contains("normalized_distance [src/lib.rs]"));
    for html in [&count, &lcom, &distance] {
        assert!(html.contains("<title>Stable Metrics</title>"));
        assert!(html.contains("Generated by ArchUnitRust"));
        assert!(!html.contains("Generated:"));
    }
}

#[test]
fn report_validation_precedes_discovery_and_preserves_selector_error_order() {
    let missing = PathBuf::from("definitely/missing");
    let output = TemporaryDirectory::new("validation");
    let invalid_options = metrics_in(missing.as_path())
        .count()
        .export_as_html_with(
            output.path().join("report"),
            &MetricsExportOptions::new().with_title(""),
        )
        .expect_err("invalid options should precede project discovery");
    let invalid_path = metrics_in(missing.as_path())
        .lcom()
        .export_as_html("")
        .expect_err("invalid output path should precede project discovery");
    let selector_first = metrics_in(missing)
        .in_path("src/[")
        .distance()
        .export_as_html_with("", &MetricsExportOptions::new().with_title(""))
        .expect_err("the earlier selector error should win");

    assert!(matches!(invalid_options, ArchUnitError::User(_)));
    assert!(
        invalid_options
            .to_string()
            .contains("title must not be empty")
    );
    assert!(
        invalid_path
            .to_string()
            .contains("output path must name a file")
    );
    assert!(
        selector_first
            .to_string()
            .contains("invalid in_path pattern")
    );
    assert!(!output.path().exists());
}
